# Generated by Django 5.2.5 on 2025-09-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('founder', 'Founder'), ('investor', 'Investor'), ('admin', 'Administrator')], default='user', max_length=20),
        ),
    ]
