# Generated by Django 5.2.5 on 2025-09-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveactivity',
            name='action',
            field=models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('rename', 'Rename'), ('move', 'Move'), ('delete', 'Delete'), ('restore', 'Restore'), ('share', 'Share'), ('unshare', 'Unshare'), ('create_folder', 'Create Folder'), ('preview', 'Preview'), ('edit', 'Edit')], help_text='The type of action performed', max_length=20),
        ),
    ]
