# Generated by Django 5.2.5 on 2025-09-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_date', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255, null=True)),
                ('startup_id', models.IntegerField(null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('news_date', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255, null=True)),
                ('startup_id', models.IntegerField(null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
