# Generated by Django 5.2.5 on 2025-09-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('dates', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=255, null=True)),
                ('target_audience', models.CharField(max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('startup_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('legal_status', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('investor_type', models.CharField(max_length=255, null=True)),
                ('investment_focus', models.CharField(max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('news_date', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255, null=True)),
                ('startup_id', models.IntegerField(null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('legal_status', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('partnership_type', models.CharField(max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StartupDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('legal_status', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website_url', models.CharField(max_length=255, null=True)),
                ('social_media_url', models.CharField(max_length=255, null=True)),
                ('project_status', models.CharField(max_length=255, null=True)),
                ('needs', models.TextField(blank=True, null=True)),
                ('sector', models.CharField(max_length=255, null=True)),
                ('maturity', models.CharField(max_length=255, null=True)),
                ('founders_images', models.JSONField(blank=True, null=True)),
                ('founders', models.ManyToManyField(related_name='startups', to='admin_panel.founder')),
            ],
        ),
    ]
