# Generated by Django 5.2.5 on 2025-09-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdetail',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
