# Generated by Django 5.2.5 on 2025-09-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_newsdetail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('dates', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=255, null=True)),
                ('target_audience', models.CharField(max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
