# Generated by Django 5.2.5 on 2025-09-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('startup_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StartupList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('legal_status', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('sector', models.CharField(max_length=255, null=True)),
                ('maturity', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartupDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('legal_status', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website_url', models.CharField(max_length=255, null=True)),
                ('social_media_url', models.CharField(max_length=255, null=True)),
                ('project_status', models.CharField(max_length=255, null=True)),
                ('needs', models.TextField(blank=True, null=True)),
                ('sector', models.CharField(max_length=255, null=True)),
                ('maturity', models.CharField(max_length=255, null=True)),
                ('founders_images', models.JSONField(blank=True, null=True)),
                ('founders', models.ManyToManyField(related_name='startups', to='admin_panel.founder')),
            ],
        ),
    ]
