# Generated by Django 5.2.5 on 2025-09-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_founder_startuplist_startupdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupdetail',
            name='founders',
            field=models.ManyToManyField(blank=True, null=True, related_name='startups', to='admin_panel.founder'),
        ),
    ]
