# Generated by Django 5.2.5 on 2025-09-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_startupdetail_founders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
