# Generated by Django 5.2.5 on 2025-09-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('legal_status', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('investor_type', models.CharField(max_length=255, null=True)),
                ('investment_focus', models.CharField(max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
