# Generated by Django 5.2.5 on 2025-09-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_investor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('legal_status', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('partnership_type', models.CharField(max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
