# Generated by Django 5.2.5 on 2025-09-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupdetail',
            name='founders',
            field=models.ManyToManyField(related_name='startups', to='admin_panel.founder'),
        ),
    ]
