# Generated by Django 5.2.5 on 2025-09-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0011_alter_event_image_alter_newsdetail_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
