# Generated by Django 5.2.5 on 2025-09-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(help_text="Brief description of the action (e.g. 'New startup registered')", max_length=255)),
                ('user', models.CharField(help_text='Name of the user who performed the action', max_length=100)),
                ('type', models.CharField(help_text='Type of the action', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
