# Generated by Django 5.2.5 on 2025-09-10 13:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('new_signups', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Site Statistics',
                'verbose_name_plural': 'Site Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the project was disliked')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the disliker (for tracking unique dislikes)', null=True)),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous users to track unique dislikes', max_length=40, null=True)),
                ('project', models.ForeignKey(help_text='The project that was disliked', on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='admin_panel.startupdetail')),
                ('user', models.ForeignKey(blank=True, help_text='The user who disliked the project (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_dislikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Dislike',
                'verbose_name_plural': 'Project Dislikes',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project'], name='exposed_api_project_ec2127_idx'), models.Index(fields=['timestamp'], name='exposed_api_timesta_a95de1_idx'), models.Index(fields=['user'], name='exposed_api_user_id_d9ba3f_idx'), models.Index(fields=['ip_address'], name='exposed_api_ip_addr_99647c_idx')],
                'unique_together': {('project', 'ip_address', 'session_key'), ('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the project was liked')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the liker (for tracking unique likes)', null=True)),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous users to track unique likes', max_length=40, null=True)),
                ('project', models.ForeignKey(help_text='The project that was liked', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='admin_panel.startupdetail')),
                ('user', models.ForeignKey(blank=True, help_text='The user who liked the project (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Like',
                'verbose_name_plural': 'Project Likes',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project'], name='exposed_api_project_a69108_idx'), models.Index(fields=['timestamp'], name='exposed_api_timesta_e924f1_idx'), models.Index(fields=['user'], name='exposed_api_user_id_8f0cd6_idx'), models.Index(fields=['ip_address'], name='exposed_api_ip_addr_da4277_idx')],
                'unique_together': {('project', 'ip_address', 'session_key'), ('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProjectShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the project was shared')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the sharer (for tracking unique shares)', null=True)),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous users to track unique shares', max_length=40, null=True)),
                ('platform', models.CharField(blank=True, help_text="Platform where the project was shared (e.g., 'facebook', 'twitter', 'linkedin')", max_length=50, null=True)),
                ('project', models.ForeignKey(help_text='The project that was shared', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='admin_panel.startupdetail')),
                ('user', models.ForeignKey(blank=True, help_text='The user who shared the project (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Share',
                'verbose_name_plural': 'Project Shares',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project'], name='exposed_api_project_8c599d_idx'), models.Index(fields=['timestamp'], name='exposed_api_timesta_154bc1_idx'), models.Index(fields=['user'], name='exposed_api_user_id_150f73_idx'), models.Index(fields=['ip_address'], name='exposed_api_ip_addr_cb70dd_idx'), models.Index(fields=['platform'], name='exposed_api_platfor_ac02a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the project was viewed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the viewer (for tracking unique views)', null=True)),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous users to track unique views', max_length=40, null=True)),
                ('project', models.ForeignKey(help_text='The project that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='admin_panel.startupdetail')),
                ('user', models.ForeignKey(blank=True, help_text='The user who viewed the project (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project View',
                'verbose_name_plural': 'Project Views',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project'], name='exposed_api_project_19375b_idx'), models.Index(fields=['timestamp'], name='exposed_api_timesta_abbf11_idx'), models.Index(fields=['user'], name='exposed_api_user_id_16f094_idx'), models.Index(fields=['ip_address'], name='exposed_api_ip_addr_08b3e8_idx')],
            },
        ),
    ]
