# Generated by Django 5.2.5 on 2025-09-05 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('exposed_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the project was viewed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the viewer (for tracking unique views)', null=True)),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous users to track unique views', max_length=40, null=True)),
                ('project', models.ForeignKey(help_text='The project that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='admin_panel.startupdetail')),
                ('user', models.ForeignKey(blank=True, help_text='The user who viewed the project (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project View',
                'verbose_name_plural': 'Project Views',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project'], name='exposed_api_project_19375b_idx'), models.Index(fields=['timestamp'], name='exposed_api_timesta_abbf11_idx'), models.Index(fields=['user'], name='exposed_api_user_id_16f094_idx'), models.Index(fields=['ip_address'], name='exposed_api_ip_addr_08b3e8_idx')],
            },
        ),
    ]
